from __future__ import annotations

NODE_RADIUS = 18
AGV_RADIUS = 11
EDGE_SELECT_RADIUS = 26
TIMER_INTERVAL_MS = 650
NODE_COMBO_MAX_VISIBLE_ITEMS = 12
CANVAS_ZOOM_STEP = 1.15
CANVAS_MIN_ZOOM = 0.20
CANVAS_MAX_ZOOM = 5.00
MOVE_NODE = "MOVE_NODE"
INTERSECTION_NODE = "INTERSECTION_NODE"
RESERVATION_NODE = "RESERVATION_NODE"
BUFFER_NODE = "BUFFER_NODE"
WAIT_NODE = "WAIT_NODE"
NORMAL_NODE = MOVE_NODE
DEFAULT_BUFFER_NODE_IDS = {7, 10}
